### ISSUE TITLE
Estructura de carpetas y distribución de archivos

### ISSUE THREAD

**Issue by aeroxmotion** [escueladigital/EDui#1]
Hola.

Creo este issue por que quisiera implementar una estructura de carpetas y una distribución de archivos diferente, que creo que es un poco más amigable con el usuario final y con los futuros desarrolladores que contribuyan a esta librería.

La estructura de carpetas quisiera que fuera tal que así:

**EDui**
&nbsp;&nbsp;&nbsp;&nbsp;**dist/** Aquí se encontrarán los archivos de los componentes ya transpilados y compilados, y listos para que los usuarios finales los usen en sus proyectos (CSS, JS, etc)
&nbsp;&nbsp;&nbsp;&nbsp;**examples/** Contendrá los ejemplos de los distintos componentes (HTML)
&nbsp;&nbsp;&nbsp;&nbsp;**src/** Esta carpeta contendrá el código fuente de los componentes (SCSS, JS, etc)

Para la distribución de archivos quiero que cada componente por carpeta contenga sus propios archivos, por ejemplo, para el componente `animated-scroll` que exista una carpeta llamada `animated-scroll` que contenga sus respectivos archivos dentro de cada una de las carpetas `dist`, `examples` y `src`.

Espero haberme hecho entender. Si me dan el visto bueno para implementar esto, realizo mi pull request.

Muchas gracias por esta librería!!! La estaba esperando con ansias. =D

**Comment by escueladigital** [comment]
Muchas gracias nuevamente por tu apoyo. Suena interesante. Donde iría el HTML para hacer las pruebas de cada componente?

**Comment by aeroxmotion** [comment]
Podría ir en una carpeta llamada "test" en la raíz del proyecto.

Quedaría algo así como:

**EDui**
&nbsp;&nbsp;&nbsp;&nbsp;**test/**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**nombre-componente.html**

Incluso estaba pensando en implementar un test runner, como karma, y un framework de testing, como jasmine, para que podamos crear y automatizar la ejecución de pruebas unitarias para los componentes. Tal
 vez ese tema deba ser tratado en otro issue. 😁
