### ISSUE TITLE
Añadir métodos de EDui a los protipos de HTML

### ISSUE THREAD

**Issue by escueladigital** [escueladigital/EDui#10]
Así no habria que llamarlos por parametros sino seleccionar el elemento y aplicarle un método. Se hace desde
HTMLElement.prototype

**Comment by aeroxmotion** [comment]
¡Hola!

Yo creería que lo mejor es que no se modificara el prototipo nativo.

Este [artículo](https://javascript.info/native-prototypes#native-prototype-change) explica mejor el porqué.

**Comment by idcmardelplata** [comment]
Coincidido con vos, pienso que en este caso pueda llegar a ser mas util un functor (al mejor estilo jquery) y asi no tocar los prototipos y poder encadenar funciones fácilmente, en estos dias voy a ver si lo hago y mando el pr correspondiente.
