### ISSUE TITLE
debug mode y production mode para enviar mensajes a consoila

### ISSUE THREAD

**Issue by escueladigital** [escueladigital/EDui#15]

**Comment by idcmardelplata** [comment]
Hola alvaro, te pareceria que prepare los test unitarios usando mocha y sinon?,  asi es mas facil refactorizar el codigo.

**Comment by escueladigital** [comment]
Nunca los he usado así que sería una buena oportunidad de aprender 😀

Dale

**Comment by idcmardelplata** [comment]
Ok, esta.noche me pongo en ello.
