### ISSUE TITLE
Generador de componentes.

### ISSUE THREAD

**Issue by idcmardelplata** [escueladigital/EDui#2]
Hola, estaba pensando en hacer un generador de componentes (por linea de comando), para que los usuarios solamente tengamos que seleccionar el componente que deseamos de una lista y el generador automáticamente lo descargue y lo ponga en una carpeta llamada "componentes" de la aplicación (o alguna carpeta elegida por el usuario).  De ese modo es mas rápido el flujo de trabajo y se quita la necesidad de tener que descargar toda la librería para poder usar un elemento. ¿que les parece?, si están de acuerdo avisen y con gusto lo comienzo a programar.

**Comment by escueladigital** [comment]
Si, suena muy bien. Por cierto, planeo tener un archivo helpers.js (o algo así) donde haya funciones reutilizables para el DOM. Por ejemplo, crear elementos, moverlos, añadir atributos, etc, que se necesitaría en cualquier componente. ¿Dónde podría ir? De hecho ya tengo varias funciones de ese archivo pero no sé donde ponerlo.

**Comment by idcmardelplata** [comment]
Hola, se podría cambiar la estructura del proyecto, y poner el codigo de los componentes en una carpeta src y los helpers en una carpeta src/utils y las librerias de terceros en una carpeta src / 3dparty y la salida compilada podría estar en un directorio dist asi creo que estaria bastante bien estructurado el proyecto (es una estructura bastante comun en éste tipo de proyectos)

**Comment by escueladigital** [comment]
si se usaran librerias de 3ros es bueno tenerlos en una carpeta o en el
package.json para instalarlos?


Álvaro Felipe Chávez

Director General (CEO)
https://ed.team
<https://ed.team/facebook> <https://ed.team/youtube>
<https://ed.team/twitter> <https://ed.team/linkedin>
<https://ed.team/github>

**Comment by idcmardelplata** [comment]
El tema es que por medio de gulp debemos minificar el codigo de esas librerias, y habría que ver que nos queda mas fácil para poder hacer eso.
