### ISSUE TITLE
Proyecto paralelo: EDdom

### ISSUE THREAD

**Issue by aeroxmotion** [escueladigital/EDui#20]
¡Hola!

Ya que la mayoría de componentes de EDui van a manipular constantemente el DOM, creo que sería una buena idea implementar una librería (para usarla en lugar del archivo helpers.js) que se encargue de manipular e interactuar con el DOM. Podría tener un API similar a la de jQuery o [Zepto.js](https://github.com/madrobby/zepto) (obviamente sin los métodos que realizan peticiones Ajax).

Mi idea es que la librería no sea exclusiva de EDui sino que pueda ser accesible para cualquier persona que la quiera usar (con o sin EDui), ya sea para reemplazar jQuery, o para tener una versión más ligera y simple para manipular elementos del DOM.

Inicialmente se me ocurrió el nombre de EDdom, pero podría tener otro nombre.

Si gusta la idea, yo podría implementar el código para esta librería. Estaré atento 😄

**Comment by escueladigital** [comment]
➤ Alvaro Felipe commented:

Suena muy chevere esa idea. Es verdad, se requieren una serie de funciones que EDui utilizará constantemente y le he dado muchas vueltas sobre como hacerlo. Si puede crecer independientemente sería espectacular. Lo único sería que este nuevo proyecto sea super minimalista (esa es la filosofía de EDgrid y EDui) y que no engorde porque si luego para usar EDui tenemos que cargarnos miles de lineas extra dejaria de ser cool

**Comment by aeroxmotion** [comment]
Yo haría la librería completamente minimalista y ligera. Igualmente podemos valernos de plugins o add-ons para extender la funcionalidad de la librería, y así, sólo importar y usar lo que se necesite.

Hoy tengo el resto del día, así que podría empezar a prototipar la librería con las funcionalidades básicas   que son usadas por EDui. El concepto de la librería se podría introducir, inicialmente, cambiando el archivo `helpers` por el prototipo de la librería.
